---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-server-admin
  namespace: dev-pipeline
  labels:
    app.kubernetes.io/instance: dev-pipeline
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
    apiGroup: ""
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: ""
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-controller-admin
  namespace: dev-pipeline
  labels:
    app.kubernetes.io/instance: dev-pipeline
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
    apiGroup: ""
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: ""