apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-app-pipeline
  namespace: dev-pipeline
  labels:
    app: quarkus
    component: tekton
spec:
  params:
    - name: deployment_environment
    - name: app-url
    - name: app-revision
    - name: manifest-url
    - name: manifest-revision
    - name: image
    - name: path-to-docker-file
    - name: path-to-yaml
    - name: path-to-yaml-image
    - name: git-user
    - name: git-email
  workspaces:
    - name: git-source
    - name: git-source-deployment
    - name: input
  tasks:
    - name: fetch-app-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.app-url)
        - name: revision
          value: $(params.app-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: fetch-deployment-manifests-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.manifest-url)
        - name: revision
          value: $(params.manifest-revision)
      workspaces:
        - name: output
          workspace: git-source-deployment
#    - name: build-image
#      taskRef:
#        name: kaniko
#      params:
#        - name: IMAGE
#          value: $(params.image)
#        - name: DOCKERFILE
#          value: $(params.path-to-docker-file)
#      workspaces:
#        - name: source
#          workspace: git-source
#      runAfter:
#        - fetch-app-from-git
    - name: replace-image
      taskRef:
        name: update-image-in-yaml
      params:
        - name: path
          value: $(params.path-to-yaml)
        - name: yamlPathToImage
          value: $(params.path-to-yaml-image)
        - name: image
          value: $(params.image)
      workspaces:
        - name: source
          workspace: git-source-deployment
      runAfter:
        - fetch-deployment-manifests-from-git
    - name: push-changes-to-git
      taskRef:
        name: git-cli
      workspaces:
        - name: source
          workspace: git-source-deployment
        - name: input
          workspace: input
      params:
        - name: GIT_USER_NAME
          value: $(params.git-user)
        - name: GIT_USER_EMAIL
          value: $(params.git-email)
        - name: GIT_SCRIPT
          value: |
            git add deployment/quarkus-app-deployment.yaml
            git commit -m 'Update deployment image'
            git push origin HEAD:master
      runAfter:
        - replace-image
    - name: argocd-sync-deployment
      params:
        - name: application-name
          value: $(params.deployment_environment)
        - name: flags
          value: '--insecure'
        - name: argocd-version
          value: v1.5.2
      runAfter:
        - push-changes-to-git
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait